[package]
name = "getver"
version = "0.2.0"
edition = "2018"
authors = ["phynalle <phynalism@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "A simple command line tool for capturing the latest version of crates"
repository = "https://github.com/phynalle/getver"
keywords = ["fetch", "crate", "version"]

[dependencies]
log = "0.4"
env_logger = "0.5"
reqwest = "0.9.2"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "0.1"
futures = "0.1.23"
colored = "1.6"
version = "3.0"
